 
export const  qariOptions = [
    {"identifier": "ar.abdulazizazzahrani", "language": "عربي", "name": "عبد العزيز الزهراني", "englishName": "Abdulaziz Az-Zahrani", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulbariaththubaity", "language": "عربي", "name": "عبد الباري الثبيتي", "englishName": "AbdulBari ath-Thubaity", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulbarimohammed", "language": "عربي", "name": "عبد الباري محمد", "englishName": "Abdul Bari Mohammed", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulbasitmujawwad", "language": "عربي", "name": "عبد الباسط عبد الصمد [مجود]", "englishName": "AbdulBaset AbdulSamad [Mujawwad]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulbasitmurattal", "language": "عربي", "name": "عبد الباسط عبد الصمد [مرتّل]", "englishName": "AbdulBaset AbdulSamad [Murattal]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulkareemalhazmi", "language": "عربي", "name": "عبد الكريم الحازمي", "englishName": "Abdul-Kareem al-Hazmi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdullahalmatrood", "language": "عربي", "name": "عبد الله المطرود", "englishName": "Abdullah al-Matrood", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdullahawadaljuhani", "language": "عربي", "name": "عبد الله الجهني", "englishName": "Abdullah Juhany", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdullahbasfar", "language": "عربي", "name": "عبد الله بصفر", "englishName": "Abdullah Basfar", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdullahkhayat", "language": "عربي", "name": "عبد الله خياط", "englishName": "Abdullah Khayat", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdullahkhulaifi", "language": "عربي", "name": "عبد الله الخليفي", "englishName": "Abdullah Khulayfee", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulmohsenalharthy", "language": "عربي", "name": "عبد المحسن الحارثي", "englishName": "Abdulmohsen Al-Harthy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulmuhsinalqasim", "language": "عربي", "name": "عبد المحسن القاسم", "englishName": "AbdulMuhsin al-Qasim", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulmunimabdulmubdi", "language": "عربي", "name": "عبد المنعم عبد المبدئ", "englishName": "Abdul-Mun'im Abdul-Mubdi'", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdulwadoodhaneef", "language": "عربي", "name": "عبد الودود حنيف", "englishName": "AbdulWadood Haneef", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdurrasheedsufiabialhaarithanalkasaaee", "language": "عربي", "name": "عبد الرشيد صوفي [أبي الحارث عن الكسائي]", "englishName": "Abdur-Rashid Sufi [Abi al-Haarith an al-Kasaa'ee]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdurrasheedsufiaddoorianabiamr", "language": "عربي", "name": "عبد الرشيد صوفي [الدوري عن أبي عمرو]", "englishName": "Abdur-Rashid Sufi [ad-Doori an Abi Amr]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdurrasheedsufishubahanasim", "language": "عربي", "name": "عبد الرشيد صوفي [شعبة عن عاصم]", "englishName": "Abdur-Rashid Sufi [Shu'bah an Asim]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdurrasheedsufisoosi", "language": "عربي", "name": "عبد الرشيد صوفي [السوسي]", "englishName": "Abdurrashid Sufi [Soosi]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abdurrazaqbinabtanaldulaimi", "language": "عربي", "name": "عبد الرزاق بن ابتان الدليمي", "englishName": "Abdur Razaq Bin Abtan Al Dulaimi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abuabdullahmuniraltounsi", "language": "عربي", "name": "أبو عبد الله منير التونسي", "englishName": "Abu Abdullah Munir Al Tounsi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.abubakraldhabi", "language": "عربي", "name": "أبو بكر الذبي", "englishName": "Abu Bakr al Dhabi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.adilkalbani", "language": "عربي", "name": "عادل الكلباني", "englishName": "Adel Kalbani", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmadalhawashy", "language": "عربي", "name": "أحمد الحواشي", "englishName": "Ahmad Al Hawashy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmadalnufais", "language": "عربي", "name": "أحمد النفيس", "englishName": "Ahmad Alnufais", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmadkhaderaltarabulsi", "language": "عربي", "name": "أحمد خضر الطرابلسي", "englishName": "Ahmad Khader Al-Tarabulsi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmadsulaiman", "language": "عربي", "name": "أحمد سليمان", "englishName": "Ahmad Suleiman", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedalajmi", "language": "عربي", "name": "أحمد بن علي العجمي", "englishName": "Ahmed ibn Ali al-Ajamy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedalhammad", "language": "عربي", "name": "أحمد الحامد", "englishName": "Ahmed Al Hammad", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedalmisbahi", "language": "عربي", "name": "أحمد المصباحي", "englishName": "Ahmed Al Misbahi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedamir", "language": "عربي", "name": "أحمد أمير", "englishName": "Ahmed Amir", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedmohamedsalama", "language": "عربي", "name": "أحمد محمد سلامة", "englishName": "Ahmed Mohamed Salama", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ahmedsaber", "language": "عربي", "name": "أحمد صابر", "englishName": "Ahmed Saber", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alafasy", "language": "عربي", "name": "مشاري راشد العفاسي", "englishName": "Mishary Rashid Alafasy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alashryomran", "language": "عربي", "name": "العشري عمران", "englishName": "Al Ashry Omran", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alfatehmuhammadzubair", "language": "عربي", "name": "الفتح محمد زبير", "englishName": "Al Fateh Muhammad Zubair", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alhusaynialazazi", "language": "عربي", "name": "الحسيني العزازي", "englishName": "Al Husayni Al Azazi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alhusaynialazazichildren", "language": "عربي", "name": "الحسيني العزازي - للأطفال", "englishName": "Al Husayni Al Azazi - Children", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.aliabdurrahmanalhuthaify", "language": "عربي", "name": "علي عبد الرحمن الحذيفي", "englishName": "Ali Abdur-Rahman al-Huthaify", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.aliabdurrahmanalhuthaifyqaloon", "language": "عربي", "name": "علي الحذيفي [قالون]", "englishName": "Ali al-Huthaify [Qaaloon]", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alihajjajsouissi", "language": "عربي", "name": "علي حجاج سويِسي", "englishName": "Ali Hajjaj Souissi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.alzainmohamedahmed", "language": "عربي", "name": "الزين محمد أحمد", "englishName": "Alzain Mohammad Ahmad", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.aymanswed", "language": "عربي", "name": "أيمن سويد", "englishName": "Ayman Swed", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.azizalili", "language": "عربي", "name": "عزيز عليلي", "englishName": "Aziz Alili", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.bandarbalila", "language": "عربي", "name": "بندر بليلة", "englishName": "Bandar Balila", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.basselabdulrahmanraoui", "language": "عربي", "name": "باسل عبد الرحمن راوي", "englishName": "Bassel Abdul Rahman Raoui", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.benkirane", "language": "عربي", "name": "عبد المجيب بن كيران", "englishName": "Abd al-Mujib Ben Kirane", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.darwishfarajdarwishalattar", "language": "عربي", "name": "درويش فرج درويش العطار", "englishName": "Darwish Faraj Darwish Al Attar", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.eidhassanabuaachra", "language": "عربي", "name": "عيد حسن أبو عيشرة", "englishName": "Eid Hassan Abu Aachra", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.emadalmansary", "language": "عربي", "name": "عماد المنصاري", "englishName": "Emad Al Mansary", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ezzatsabri", "language": "عربي", "name": "عزت صبري", "englishName": "Ezzat Sabri", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.faresabbad", "language": "عربي", "name": "فارس عباد", "englishName": "Fares Abbad", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.fouadalkhamiri", "language": "عربي", "name": "فؤاد الخميري", "englishName": "Fouad Al Khamiri", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.hamadsinan", "language": "عربي", "name": "حمد سنان", "englishName": "Hamad Sinan", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.hamdyalsayedtolbasaad", "language": "عربي", "name": "حمدي السيد طلبة سعد", "englishName": "Hamdy Al Sayed Tolba Saad", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.haniarrifai", "language": "عربي", "name": "هاني الرفاعي", "englishName": "Hani ar-Rifai", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.hasanhashem", "language": "عربي", "name": "حسن هاشم", "englishName": "Hasan Hashem", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.hassansaleh", "language": "عربي", "name": "حسن صالح", "englishName": "Hasan Saleh", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.hatemfarid", "language": "عربي", "name": "حاتم فريد", "englishName": "Hatem Farid", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ibrahimalakhdar", "language": "عربي", "name": "إبراهيم الأخضر", "englishName": "Ibrahim Al Akhdar", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ibrahimaldossari", "language": "عربي", "name": "إبراهيم الدوسري", "englishName": "Ibrahim Al Dossari", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ibrahimaljormy", "language": "عربي", "name": "إبراهيم الجرمي", "englishName": "Ibrahim Aljormy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.ilhantok", "language": "عربي", "name": "إلهان توك", "englishName": "Ilhan Tok", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.imadzuhairhafez", "language": "عربي", "name": "عماد زهير حافظ", "englishName": "Imad Zuhair Hafez", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.jaberabdulhameed", "language": "عربي", "name": "جابر عبد الحميد", "englishName": "Jaber Abdul Hameed", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.jamaanalosaimi", "language": "عربي", "name": "جمان العثيمي", "englishName": "Jamaan Alosaimi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.jamalshakerabdullah", "language": "عربي", "name": "جمال شاكر عبد الله", "englishName": "Jamal Shaker Abdullah", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.jazzaalswaileh", "language": "عربي", "name": "جزا السويلح", "englishName": "Jazza Alswaileh", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.kamel", "language": "عربي", "name": "عبد الله كامل", "englishName": "Abdallah Kamel", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.karimmansouri", "language": "عربي", "name": "كريم منصوري", "englishName": "Karim Mansouri", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khaledalqahtani", "language": "عربي", "name": "خالد عبد الله القحطاني", "englishName": "Khaalid Abdullaah al-Qahtaanee", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khaledbarakat", "language": "عربي", "name": "خالد بركات", "englishName": "Khaled Barakat", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khalidabdulkafi", "language": "عربي", "name": "خالد عبد الكافي", "englishName": "Khalid Abdulkhafi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khalidaljalil", "language": "عربي", "name": "خالد الجليل", "englishName": "Khalid Al Jalil", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khalidalmohanna", "language": "عربي", "name": "خالد المهنا", "englishName": "Khalid Al-Moh'n'na", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.khalifaaltunaiji", "language": "عربي", "name": "خليفة الطنيجي", "englishName": "Khalifah At-Tonaeijy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.laayounelkouchi", "language": "عربي", "name": "ليَعْيُون الكوشي", "englishName": "Laayoun El Kouchi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.lesaintcorantraduitenfrancais", "language": "عربي", "name": "القرآن الكريم مترجم إلى الفرنسية", "englishName": "Le Saint Coran Traduit En Francais", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahershakhashiro", "language": "عربي", "name": "ماهر شاخاشيرو", "englishName": "Maher Shakhashero", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahmoodalrifai", "language": "عربي", "name": "محمود الرفاعي", "englishName": "Mahmod Alrifai", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahmoudalialbanna", "language": "عربي", "name": "محمود علي البنا", "englishName": "Mahmud Ali Al Banna", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahmoudelsheimy", "language": "عربي", "name": "محمود الشيمي", "englishName": "Mahmoud El Sheimy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahmoudsaaddarouich", "language": "عربي", "name": "محمود سعد درويش", "englishName": "Mahmoud Saad Darouich", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mahmoudsayedeltayeb", "language": "عربي", "name": "محمود سيد الطيب", "englishName": "Mahmoud Sayed Eltayeb", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.misharyrashidalafasy", "language": "عربي", "name": "مشاري راشد العفاسي", "englishName": "Mishary Rashid Alafasy", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.moeedhalharthi", "language": "عربي", "name": "معيض الحارثي", "englishName": "Moeedh Al-Harthi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedabdelaziz", "language": "عربي", "name": "محمد عبد العزيز", "englishName": "Mohamed Abdelaziz", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedabdelhakimsaadalabdullah", "language": "عربي", "name": "محمد عبد الحكيم سعد العبد الله", "englishName": "Mohamed Abdel Hakim Saad Al Abdullah", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedaljaberyalheyani", "language": "عربي", "name": "محمد الجابري الهياني", "englishName": "Mohamed Aljabery Al Heyani", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedalmohisni", "language": "عربي", "name": "محمد المحيسني", "englishName": "Mohamed Al Mohisni", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedelkantaoui", "language": "عربي", "name": "محمد القنتاوي", "englishName": "Mohamed El Kantaoui", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedhassan", "language": "عربي", "name": "محمد حسن", "englishName": "Muhammad Hassan", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedmaabad", "language": "عربي", "name": "محمد معبد", "englishName": "Mohamed Maabad", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedosmankhan", "language": "عربي", "name": "محمد عثمان خان (من الهند)", "englishName": "Mohammed Osman Khan (from India)", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedshaabanabuqarn", "language": "عربي", "name": "محمد شعبان أبو قرن", "englishName": "Mohamed Shaaban Abu Qarn", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohamedtablawi", "language": "عربي", "name": "محمد الطبلاوي", "englishName": "Mohamed Al-Tablawi", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohammadismaeelalmuqaddim", "language": "عربي", "name": "محمد إسماعيل المقدم", "englishName": "Mohammad Ismaeel Al-Muqaddim", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohammadrachadalshareef", "language": "عربي", "name": "محمد رشاد الشريف", "englishName": "Mohammad Rachad Al Shareef", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.mohammedbinsalehabuzaid", "language": "عربي", "name": "محمد بن صالح أبو زيد", "englishName": "Mohammed Bin Saleh Abu Zaid", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.muftahalsaltany", "language": "عربي", "name": "مفتاح السلطني", "englishName": "Moftah AlSultany", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.muhammadabdulkareem", "language": "عربي", "name": "محمد عبد الكريم", "englishName": "Muhammad AbdulKareem", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.muhammadalaalimaldokali", "language": "عربي", "name": "محمد العالم الدكالي", "englishName": "Muhammad Al Aalim Al Dokali", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.muhammadalluhaidan", "language": "عربي", "name": "محمد اللحيدان", "englishName": "Mohammad Al-Haid'an", "format": "audio", "type": "surahbysurah", "bitrate": "128"},
    {"identifier": "ar.muhammadalmehysni", "language": "عربي", "name": "محمد المحيسني", "englishName": "Muhammad al-Muhaisny", "format": "audio", "type": "surahbysurah", "bitrate": "128"}
   ]